# Generated by Django 5.1.3 on 2024-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_password_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='cc22a66df51c47b58641efaa', primary_key=True, serialize=False, unique=True),
        ),
    ]
