# Generated by Django 5.1.3 on 2024-12-01 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99c5d5ab-3bb6-40aa-8bf8-3905d9790ba8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
